# Generated by Django 2.2.5 on 2019-09-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сontent', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('likert', 'likert'), ('fc', 'forced-choice')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('sum', 'sum'), ('avg', 'average')], default='avg', max_length=10)),
                ('items', models.ManyToManyField(through='psytests.Question', to='psytests.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MockUser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.Scale'),
        ),
        migrations.CreateModel(
            name='Psytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('instruction', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MockUser')),
                ('scales', models.ManyToManyField(to='psytests.Scale')),
            ],
        ),
    ]
