# Generated by Django 2.2.5 on 2019-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuser',
            name='name',
            field=models.CharField(default='STUPID', max_length=20),
            preserve_default=False,
        ),
    ]
